name: youtube-search
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - pip
  - pip:
    - openai-whisper==20231117
    - yt-dlp==2024.4.9
    - g2p-en==2.1.0
    - torch==2.2.1
    - torchvision==0.17.1
    - torchaudio==2.2.1
    - whisper-timestamped==1.14.4
    - faster-whisper==1.0.1
    - flask==3.0.1
    - flask-cors==4.0.0
    - pandas==2.2.0
